Provide mode flag to ResetToInitialConditions() to skip the execution of RunIC()
JSBSim-Team/jsbsim pull request #466
Opened 2021-07-03 12:37 UTC by seanmcleod

See https://github.com/JSBSim-Team/jsbsim/discussions/455#discussioncomment-959614

2021-07-07 22:37 UTC, bcoconni requested changes
Thanks for the PR. I suggest to move the constants to the header `FGFDMExec.h` where they could be documented and therefore easier to get for someone looking for guidance about how to use `FGFDMExec::ResetToInitialConditions`.

2021-07-07 22:37 UTC, bcoconni commented on src/FGFDMExec.cpp
> +  const int DONT_EXECUTE_RUN_IC = 0x2;
```suggestion
```
May be we should take the opportunity of your PR to locate **and document** these constants in the header `FGFDMExec.h` ? Currently, only the most motivated users could unearth the existence of these constants and their role.

2021-07-08 08:39 UTC, seanmcleod commented
@bcoconni I was in a bit of a rush originally. I've moved the constants to the header file and added some documentation in the latest commit.

2021-07-10 10:28 UTC, bcoconni approved these changes
Thanks for updating the code.

2021-07-10 10:29 UTC, merged