Mingw enhancement
JSBSim-Team/jsbsim pull request #548
Opened 2021-12-28 15:53 UTC by scienceasdf

Support for MinGW python extension build and matlab mex file build.

2021-12-28 17:05 UTC, bcoconni requested changes
Thanks for the PR.

Some modifications to your code are needed since you are requesting manual modifications to Python/Anaconda files which is not our way to proceed. Instead this should be handled automatically by overloading the `distutils` compiler code.

Also we should trigger the CI compilation of Python modules for MinGW (which basically consists in reversing the commit 10530b9905738fec00d6b97b0de42167716b550f) to check that the build of the Python modules is successful.

2021-12-28 17:08 UTC, bcoconni commented
FYI we previously investigated how to build Python modules with MinGW (see issue #285) but came to the conclusion that this was not feasible since Python officially dropped the support of MinGW. I'd be interested to have your feedback about the discussion we had in issue #285, and I'd be very glad if we could work around these limitations with your PR.

2021-12-29 15:50 UTC, closed without merging

2021-12-29 15:50 UTC, scienceasdf commented on python/fpectl/setup.py.in
> +    cpp_compile_flags = ['-std=c++11', '-D_hypot=hypot']
Thanks for your review. 

I use this macro as `Python.h`  header file declares `::hypot` function. I'm using anaconda with python 3.6, whose distutils may contain some modification code. 

I close this PR for the moment. My branch will be working in progress for better MinGW compability support, to pass the CI python module building. If any new findings, I will be back here.:grin:

2021-12-29 16:30 UTC, bcoconni commented on python/fpectl/setup.py.in
> +    cpp_compile_flags = ['-std=c++11', '-D_hypot=hypot']
Ha OK, I did not think to check `Python.h`. That's a good point :smile:

2021-12-29 16:31 UTC, bcoconni commented on python/fpectl/setup.py.in
> +    cpp_compile_flags = ['-std=c++11', '-D_hypot=hypot']
And we'll be more than happy to provide you some help so do not hesitate to re-open this PR if you need some support.